site_name: Python implemented methods to solve ordinary diferential equations (ODEs)

theme: 
  name: "material"

nav: 
  - index.md
  - reference.md

markdown_extensions:
  - markdown_katex

plugins:
  - mkdocstrings
