site_name: Python implemented methods to solve ordinary diferential equations (ODEs)

theme: 
  name: "material"

nav: 
  - index.md
  - reference.md

markdown_extensions:
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.arithmatex


plugins:
  - mkdocstrings
