site_name: Python implemented methods to solve ordinary diferential equations (ODEs)

theme: 
  name: "material"

nav: 
  - index.md
  - reference.md

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

plugins:
  - mkdocstrings
