site_name: Python implemented methods to solve ordinary diferential equations (ODEs)

theme: 
  name: "material"

nav: 
  - index.md
  - reference.md

markdown_extensions:
  - toc:
      permalink: true
      permalink_class: toc-permalink

plugins:
  - mkdocstrings
